on:
  push:
    tags:
      - 'v\d+\.\d+\.\d+'
jobs:
  publish-to-nuget:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Build
        run: dotnet build -c Release --version ${VERSION}
      - name: Test
        run: dotnet test -c Release --no-build --version ${VERSION}
      - name: Pack
        run: dotnet pack -c Release --no-build --version ${VERSION} -o artifacts
      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}
      - name: NuGet push
        run: dotnet nuget push artifacts/*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
